<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div</name>
   <tag></tag>
   <elementGuidId>e347f568-0007-4dff-a576-5c9626e15109</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fixedban > div > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='fixedban']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1d5a0fab-f418-4034-a573-b0b1a3c56478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fixedban&quot;)/div[1]/div[1]</value>
      <webElementGuid>306c5a92-3c44-4ec4-afde-e01692ed985c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fixedban']/div/div</value>
      <webElementGuid>81b83580-44da-4bc7-875f-43f02fb0caae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Practice Form'])[1]/preceding::div[4]</value>
      <webElementGuid>ba651989-3aa2-4fa3-a6dd-02fb508693d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Elements'])[1]/preceding::div[6]</value>
      <webElementGuid>98806c9d-9d4c-435b-9c0c-b23c05559da8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div</value>
      <webElementGuid>e615eb2d-bf97-4202-ad38-965b2f8175a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
